include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - firebase/client_reference/**
    - prototype/**
    - "**/*.g.dart"

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
